### ISSUE TITLE
requirements.txt missing

### ISSUE THREAD

**Issue by soerface** [flipdot/ascii-flyers#2]
The readme says I should install the packages from the requirements.txt. There is no requirements.txt

**Comment by dargmuesli** [comment]
See 25b0cd5de3837648309cb6d407364789cf7902a9.

**Comment by nikeee** [comment]
https://github.com/flipdot/ascii-flyers/commit/25b0cd5de3837648309cb6d407364789cf7902a9#commitcomment-36964923

**Comment by dargmuesli** [comment]
ja den auch 😄
